In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
## Sentences

sent =[ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meanining of words',
        'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meanining of words',
 'your videos are good']

In [5]:
## Define the vocabulary size

voc_size = 10000

In [6]:
## One hot representation

one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr


[[9894, 8536, 8125, 8460],
 [9894, 8536, 8125, 2272],
 [9894, 8449, 8125, 2865],
 [2850, 3023, 2915, 9034, 184],
 [2850, 3023, 2915, 9034, 8289],
 [5805, 9894, 2790, 8125, 1867],
 [3522, 5920, 645, 9034]]

In [7]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen = sent_length)

print(embedded_docs)

[[   0    0    0    0 9894 8536 8125 8460]
 [   0    0    0    0 9894 8536 8125 2272]
 [   0    0    0    0 9894 8449 8125 2865]
 [   0    0    0 2850 3023 2915 9034  184]
 [   0    0    0 2850 3023 2915 9034 8289]
 [   0    0    0 5805 9894 2790 8125 1867]
 [   0    0    0    0 3522 5920  645 9034]]


In [10]:
## Feature Representation
dim = 10


In [14]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam', 'mse')

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 692ms/step


array([[[ 0.01817619,  0.04065764,  0.00156988, -0.02632991,
          0.04100989, -0.00066011, -0.04405366, -0.04787936,
          0.01210178, -0.04213079],
        [ 0.01817619,  0.04065764,  0.00156988, -0.02632991,
          0.04100989, -0.00066011, -0.04405366, -0.04787936,
          0.01210178, -0.04213079],
        [ 0.01817619,  0.04065764,  0.00156988, -0.02632991,
          0.04100989, -0.00066011, -0.04405366, -0.04787936,
          0.01210178, -0.04213079],
        [ 0.01817619,  0.04065764,  0.00156988, -0.02632991,
          0.04100989, -0.00066011, -0.04405366, -0.04787936,
          0.01210178, -0.04213079],
        [-0.02163992, -0.02693877, -0.0206319 , -0.01851077,
          0.04728714, -0.03223554,  0.04266741, -0.04945257,
         -0.03818426, -0.01681868],
        [ 0.01613703,  0.04317682,  0.02585191,  0.00563232,
         -0.00995325,  0.03787446,  0.04838616,  0.04895777,
          0.00724907, -0.03419268],
        [-0.04870414,  0.04445192,  0.03134428, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 9894, 8536, 8125, 8460])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 90ms/step


array([[ 0.01817619,  0.04065764,  0.00156988, -0.02632991,  0.04100989,
        -0.00066011, -0.04405366, -0.04787936,  0.01210178, -0.04213079],
       [ 0.01817619,  0.04065764,  0.00156988, -0.02632991,  0.04100989,
        -0.00066011, -0.04405366, -0.04787936,  0.01210178, -0.04213079],
       [ 0.01817619,  0.04065764,  0.00156988, -0.02632991,  0.04100989,
        -0.00066011, -0.04405366, -0.04787936,  0.01210178, -0.04213079],
       [ 0.01817619,  0.04065764,  0.00156988, -0.02632991,  0.04100989,
        -0.00066011, -0.04405366, -0.04787936,  0.01210178, -0.04213079],
       [-0.02163992, -0.02693877, -0.0206319 , -0.01851077,  0.04728714,
        -0.03223554,  0.04266741, -0.04945257, -0.03818426, -0.01681868],
       [ 0.01613703,  0.04317682,  0.02585191,  0.00563232, -0.00995325,
         0.03787446,  0.04838616,  0.04895777,  0.00724907, -0.03419268],
       [-0.04870414,  0.04445192,  0.03134428, -0.0081849 , -0.01732017,
        -0.04696863, -0.00110971,  0.03825057